require "language/node"

# Homebrew formula for the Loom CLI (published on npm as "loomctl", exposes the "loom" command).
# GENERATED by scripts/generate-manifests.mjs from the root package.json version — do not hand-edit
# the version/url; re-run the generator after `npm version` and fill the sha256 (see the runbook).
class Loomctl < Formula
  desc "Local-first AI project workspace for Claude Code, Obsidian, and tasks"
  homepage "https://github.com/DanielC000/loom"
  url "https://registry.npmjs.org/loomctl/-/loomctl-0.4.2.tgz"
  sha256 "REPLACE_WITH_SHA256_OF_PUBLISHED_ARTIFACT"
  license "MIT"

  depends_on "node@22"

  def install
    system "npm", "install", *std_npm_args
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

  test do
    assert_match "v#{version}", shell_output("#{bin}/loom --version")
  end
end
